name : AndroidBuild
on:
  pull_request :
    branches : [ main ]
  push :
    branches : [ main ]

jobs:
  build:
    runs-on : windows-latest
    steps :
      - name : Checkout
        uses: actions/checkout@v4

      - name : Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Checking lint
        run: ./gradlew lint

      - name: Build debug APK
        run: ./gradlew clean assembleDebug

      - name : Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name : HearableCICD.apk
          path : app/build/outputs/apk/debug/app-debug.apk